Repository WMass/cmgtools-lite, pull requests merged in 2018-03, with the labels that each got.

#94 Tiny trees (and friends)
  WMass/python/plotter/skimFTrees.py
  WMass/python/plotter/w-helicity-13TeV/skims.py
  WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-80X-skims.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/skim_alwaystrue.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/systsEnv.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/varsSkim_80X_helicity.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/varsSkim_80X_helicity_friends.txt
Labels: friends, production

#96 Parallelization of the PDF systematics
  WMass/python/plotter/makeShapeCards.py
  WMass/python/plotter/w-helicity-13TeV/make_helicity_cards.py
  WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-80X-wenu-helicity.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-includes/mca-data-legacy2016.txt
Labels: fit

#101 Propagate the PDF systematic uncertainties to datacards
  WMass/python/plotter/w-helicity-13TeV/DatacardsChecker.py
  WMass/python/plotter/w-helicity-13TeV/DatacardsTools.py
  WMass/python/plotter/w-helicity-13TeV/mergeCardComponentsAbsY.py
Labels: fit

#105 Symmetrization of each PDF variation
  WMass/python/plotter/w-helicity-13TeV/diffNuisances.py
  WMass/python/plotter/w-helicity-13TeV/make_helicity_cards.py
  WMass/python/plotter/w-helicity-13TeV/mergeCardComponentsAbsY.py
Labels: fit

#106 Better indexing for PDF systematics
  WMass/python/plotter/w-helicity-13TeV/DatacardsChecker.py
  WMass/python/plotter/w-helicity-13TeV/mergeCardComponentsAbsY.py
  WMass/python/plotter/w-helicity-13TeV/wmass_e/skim_zee.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/wenu_plots.txt
Labels: fit

#107 Basic tools for toy MC
  WMass/python/plotter/w-helicity-13TeV/DatacardsChecker.py
  WMass/python/plotter/w-helicity-13TeV/plotParametersFromToys.py
  WMass/python/plotter/w-helicity-13TeV/submitToys.py
Labels: enhancement, fit

#115 Adding charges combination in datacard merger
  WMass/python/plotter/w-helicity-13TeV/diffNuisances.py
  WMass/python/plotter/w-helicity-13TeV/mergeCardComponentsAbsY.py
Labels: fit

#117 Remove channel name in the norm rateParams to combine el/mu
  WMass/data/efficiency/mc_reco_eff.root
  WMass/python/plotter/w-helicity-13TeV/mergeCardComponentsAbsY.py
Labels: electron channel, fit

#118 Fix longitudinal W efficiency nuisance names for comb and effective sigma in toys plots
  WMass/python/plotter/w-helicity-13TeV/mergeCardComponentsAbsY.py
  WMass/python/plotter/w-helicity-13TeV/plotParametersFromToys.py
Labels: bug, fit

#120 Some implementation of lumi and fixed W bins uncertainties
  WMass/python/plotter/w-helicity-13TeV/mergeCardComponentsAbsY.py
  WMass/python/plotter/w-helicity-13TeV/plotYsyst.py
Labels: fit

#122 Updates, fixes and some new macros
  WMass/data/efficiency/mc_reco_LO_eff.root
  WMass/data/efficiency/mc_reco_pfmt30_eff.root
  WMass/data/efficiency/mc_reco_pfmt40_eff.root
  WMass/data/efficiency/mc_reco_pfmt50_eff.root
  WMass/python/plotter/functions.cc
  WMass/python/plotter/runfakerateElectron.sh
  WMass/python/plotter/runplotsElectron.sh
  WMass/python/plotter/utilityMacros/interface/utility.h
  WMass/python/plotter/utilityMacros/src/createShapeFile_MCasDataObs.C
  WMass/python/plotter/utilityMacros/src/makeEffStudy.C
  WMass/python/plotter/utilityMacros/src/makeFakeRateGraphPlotsAndSmoothing.C
  WMass/python/plotter/utilityMacros/src/makeVariableEfficiencyAndROC.C
  WMass/python/plotter/utilityMacros/src/plotEfficiency.C
  WMass/python/plotter/w-helicity-13TeV/hadd_wy.py
  WMass/python/plotter/w-helicity-13TeV/make_fake_rates_xvars.txt
  WMass/python/plotter/w-helicity-13TeV/symmetrizeMatrixAbsY.py
  WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-80X-wenu-helicity.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-80X_V3.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-80X_V3_FRcheck.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/test_plots.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/wenu_80X.txt
Labels: electron channel

#125 Use the new R9 granular scale corrections for electrons in Legacy2016
  WMass/python/plotter/w-helicity-13TeV/mergeCardComponentsAbsY.py
  WMass/python/postprocessing/data/leptonScale/el/Legacy2016_07Aug2017_FineEtaR9_ele_scales.dat
  WMass/python/postprocessing/data/leptonScale/el/Legacy2016_07Aug2017_FineEtaR9_ele_smearings.dat
  WMass/python/postprocessing/examples/lepVarProducer.py
Labels: electron channel

#126 A bunch of changes for electron channel only
  .gitignore
  WMass/data/fakerate/fakeRateSmoothed_el.root
  WMass/python/plotter/w-helicity-13TeV/functionsWMass.cc
  WMass/python/plotter/w-helicity-13TeV/wmass_e/skim_zee.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/wenu_80X.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/wmass_plots.py
  WMass/python/plotter/w-helicity-13TeV/zFitter.py
  WMass/python/postprocessing/data/leptonScale/el/Legacy2016_07Aug2017_FineEtaR9_ele_scales.dat
  WMass/python/postprocessing/data/leptonScale/el/plot_dm_diff.root
  WMass/python/postprocessing/data/leptonScale/el/plot_sigma_diff.root
  WMass/python/postprocessing/examples/lepVarProducer.py
  WMass/python/postprocessing/postproc_batch.py
Labels: electron channel
