Repository WMass/cmgtools-lite, pull requests merged in 2018-11, with the labels that each got.

#363 fix a couple of small things in card maker
  WMass/python/plotter/w-helicity-13TeV/make_helicity_cards.py
Labels: bug, fit

#364 Fix DC checker resubmission and move to preFSR in the DC submission
  WMass/python/plotter/w-helicity-13TeV/DatacardsChecker.py
  WMass/python/plotter/w-helicity-13TeV/make_helicity_cards.py
Labels: bug, fit

#365 vaffa to EOS, ROOT and Co.
  WMass/python/plotter/mcAnalysis.py
Labels: enhancement

#368 Use TXNetFile and AsyncReading to open the ROOT file to pick the counter histo
  WMass/python/plotter/archiveTreeDirOnAFS.py
  WMass/python/plotter/mcAnalysis.py
  WMass/python/plotter/tree2yield.py
Labels: enhancement, production

#369 small fix to AFS archive
  WMass/python/plotter/archiveTreeDirOnAFS.py
Labels: bug

#382 Updates and fixes: largely speeding up running on tree with toys
  WMass/python/plotter/runplotsElectron.sh
  WMass/python/plotter/w-helicity-13TeV/DatacardsChecker.py
  WMass/python/plotter/w-helicity-13TeV/makeNewBranchToyTree.py
  WMass/python/plotter/w-helicity-13TeV/make_diff_xsec_cards.py
  WMass/python/plotter/w-helicity-13TeV/mergeCardComponentsDiffXsec.py
  WMass/python/plotter/w-helicity-13TeV/plotDiffXsecChargeAsymmetry.py
  WMass/python/plotter/w-helicity-13TeV/plotParametersFromToys.py
  WMass/python/plotter/w-helicity-13TeV/printMCAforXsec.py
  WMass/python/plotter/w-helicity-13TeV/utilities.py
  WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-80X_forPlots.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/mca-includes/mca-80X-wenu-bkgmc.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/skimming/tests/mca-80X-skimsFR_31July2018.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/skimming/tests/wenu-80X-skim_fullsel.txt
  WMass/python/plotter/w-helicity-13TeV/wmass_e/test_plots.txt
Labels: enhancement, fit

#389 small fixes
  WMass/python/plotter/w-helicity-13TeV/mergeCardComponentsAbsY.py
  WMass/python/plotter/w-helicity-13TeV/mergeCardComponentsDiffXsec.py
Labels: bug

#391 Normalized xsecs with the correct variable from the Hessians
  WMass/python/plotter/w-helicity-13TeV/plotYW.py
Labels: enhancement

#399 Add back the possibility to fix the long W as bkg
  WMass/python/plotter/w-helicity-13TeV/mergeCardComponentsAbsY.py
Labels: fit

#400 Fix normalizations for Rapidity plots
  WMass/python/plotter/results_config_el.txt
  WMass/python/plotter/w-helicity-13TeV/plotYW.py
  WMass/python/plotter/w-helicity-13TeV/utilities.py
Labels: bug, fit

#401 fix some theo systs in the cards merger
  WMass/python/plotter/w-helicity-13TeV/mergeCardComponentsAbsY.py
Labels: bug, fit

#402 postFitPlots update
  WMass/python/plotter/w-helicity-13TeV/postFitPlots.py
Labels: enhancement, fit
